version: '3'

services:

    key_manager_rest:
        build:
            dockerfile: ./Dockerfile
            context: .
        image: fmchagas/key_manager_rest
        container_name: key_manager_rest
        ports:
            - 8080:8080
        environment:
            - KEY_MANAGER_HOST=host.docker.internal
            #- KEY_MANAGER_PORT=50051
            #- SERVER_PORT=8080