micronaut:
  application:
    name: orangeTalents04TemplatePixKeymanagerRest
  server:
    port: ${SERVER_PORT:8080}

# pool conection gRPC
grpc:
  client:
    plaintext: true
    max-retray-attempts: 10
  channels:
    key_manager_grpc_client:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'
      plaintext: true #não tenho ssl
      max-retray-attempts: 5

##
# Jackson configuration
# https://github.com/micronaut-projects/micronaut-core/issues/240
# https://geowarin.com/correctly-handle-jsr-310-java-8-dates-with-jackson/
# https://www.baeldung.com/jackson-serialize-dates
##
jackson:
  serialization:
    writeDatesAsTimestamps: false

endpoints:
#  all:
#    sensitive: false
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  env:
    enabled: false    # default: true
    sensitive: false  # default: true