micronaut:
  application:
    name: orangeTalents04TemplatePixKeymanagerRest

# pool conection gRPC
grpc:
  client:
    plaintext: true
    max-retray-attempts: 10
  channels:
    key_manager_grpc_client:
      address: 'localhost:50051'
      plaintext: true #não tenho ssl
      max-retray-attempts: 5