micronaut:
  application:
    name: orangeTalents04TemplatePixKeymanagerRest
datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/key_manager_rest?createDatabaseIfNotExist=true`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PWD:root}

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true